### PR TITLE
Accumulate unfinished messages by (displayName, id) instead of just by id

### LINKED ISSUE #3: Concurrent multi-frame messages can get corrupted
This is the error that's happening:

```
  assert: Attempt to read past end of buffer
  stack traceback:
  [C]: in function 'assert'
  percache:/AddOnsManaged/39644437-95e9-414a-adf6-578b31771ea0/LibGroupBroadcast/BinaryBuffer.lua:155: in function 'BinaryBuffer:ReadUInt'
  <Locals> self = [table:1]{bitLength = 1088, cursor = 1079}, numBits = 30 </Locals>
  percache:/AddOnsManaged/39644437-95e9-414a-adf6-578b31771ea0/LibGroupBroadcast/protocol/NumericField.lua:164: in function 'NumericField:Deserialize'
  <Locals> self = [table:2]{maxSendValue = 1073741823, label = "damage", index = 0, minValue = 0, numBits = 30, maxValue = 1073741823}, data = [table:1] </Locals>
  percache:/AddOnsManaged/39644437-95e9-414a-adf6-578b31771ea0/LibGroupBroadcast/protocol/TableField.lua:80: in function 'TableField:Deserialize'
  <Locals> self = [table:3]{label = "bossDamage", index = 0}, data = [table:1], value = [table:4]{bossTag = 8, tagSeq = 0}, i = 3, field = [table:2] </Locals>
  percache:/AddOnsManaged/39644437-95e9-414a-adf6-578b31771ea0/LibGroupBroadcast/protocol/ArrayField.lua:108: in function 'ArrayField:Deserialize'
  percache:/AddOnsManaged/39644437-95e9-414a-adf6-578b31771ea0/LibGroupBroadcast/protocol/Protocol.lua:240: in function 'Protocol:Receive'
  percache:/AddOnsManaged/39644437-95e9-414a-adf6-578b31771ea0/LibGroupBroadcast/ProtocolManager.lua:244: in function 'ProtocolManager:HandleDataMessages'
  percache:/AddOnsManaged/39644437-95e9-414a-adf6-578b31771ea0/LibGroupBroadcast/BroadcastManager.lua:170: in function 'BroadcastManager:OnDataReceived'
```
(sorry for locals not being there for half of the stack trace, UI error window doesn't really want to show everything on console)

Also, `bossTag = 8` value that we see in locals is incorrect: `bossTag = 0` was transmitted.

This is reproduced reliably by two group members sending long messages that are guaranteed to span multiple frames at the same time (in my case, it's triggered on combat end, which makes it perfectly synced). Having only one person seems to work: if you're the only one sending data, it arrives back to you perfectly intact, gets deserialised, and has the correct values.

I suspect that the issue is how FrameHandler handles unfinished messages ([here](https://github.com/sirinsidiator/ESO-LibGroupBroadcast/blob/main/src/FrameHandler.lua#L201)): looks like `unfinishedFlexMessagesById` is keyed by protocol id, so messages from different senders get concatenated together instead of being assembled separately

### PR DESCRIPTION
**Pull request by vladislavsheludchenkov**
Resolves #3

I chose displayName as a part of the key as it allows to tolerate group composition change mid-message, but let me know if you think it's an overkill. Will be happy to change it to use unitTag instead (which will work most of the time) in that case

### CODE REVIEW

File: src/FrameHandler.lua [hunk 1]
```diff
@@ -142,7 +151,7 @@ function FrameHandler:Serialize()
     return self.data
 end
 
-function FrameHandler:Deserialize(buffer)
+function FrameHandler:Deserialize(buffer, senderTag)
```
Comment (sirinsidiator) [inline src/FrameHandler.lua]: I'd prefer if the parameters were swapped, so they are in line with OnDataReceived and HandleCustomEventMessages

File: src/FrameHandler.lua [hunk 2]
```diff
@@ -24,12 +24,21 @@ local HEADER_BYTES = 2
 local FRAME_PROTOCOL_VERSION = 1
 local CHECKSUM_PLACEHOLDER_VALUE = 2 ^ 3 - 1
 
+local function ResolveSenderUnfinishedFlexMessages(unfinishedFlexMessages, senderTag)
```
Comment (sirinsidiator) [inline src/FrameHandler.lua]: This should just be a method on the class, so you don't have to pass unfinishedFlexMessages in.

File: src/FrameHandler.lua [hunk 3]
```diff
@@ -24,12 +24,21 @@ local HEADER_BYTES = 2
...
+    local displayName = GetUnitDisplayName and GetUnitDisplayName(senderTag)
```
Comment (sirinsidiator) [inline src/FrameHandler.lua]: I am all for defensive programming, but it should be safe to assume that GetUnitDisplayName exists 😅.

**Review by sirinsidiator — COMMENTED** [review]
Thanks for the PR. Not sure how I missed that, but it explains some errors. I'll merge it after you took care of the comments.

**Comment by sirinsidiator** [comment]
I've also pushed some local changes just now, you should rebase or merge your branch.

File: src/FrameHandler.lua (hunk 3 above)
Comment (vladislavsheludchenkov) [reply src/FrameHandler.lua]: I was mostly thinking about ESOLua, but probably should've checked if it supports it or not before writing this 😅

**Comment by vladislavsheludchenkov** [comment]
Thanks a lot for the feedback and for quick review!

File: src/FrameHandler.lua (hunk 3 above)
Comment (sirinsidiator) [reply src/FrameHandler.lua]: irc I added it there, but even if something missing, I feel it would be better to just add support to ESOLua than working around it  :)
